### ISSUE TITLE
Broken URLs in README

### ISSUE THREAD

**Issue by aaronmueller** [zharry29/wikihow-intent#2]
The links to the dataset (https://drive.google.com/drive/folders/1QbzEf-1yOz91lEonahVLf082zwuOJ4rj?usp=sharing) and Colab notebook (https://colab.research.google.com/drive/1zF-BMz_16WZIvpKdqcLSNIzShMuNOso2) in the README are no longer valid.

The huggingface models are still accessible, and the links in the provided `.ipynb` notebook still work.

**Comment by zharry29** [comment]
Thanks for pointing this out! I have fixed the links.
